name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.11.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.0.15
  path: ^1.8.3
  http: ^1.1.0
  pdf: ^3.10.4
  csv: ^5.0.2
  printing: ^5.11.0
  file_saver: ^0.2.9
  provider: ^6.0.5
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.11.0
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  uses-material-design: true
