#databases:
#  - name: my-postgres-db
#    databaseName: inventory_db
#    user: postgres
#
#services:
#  - type: web
#    name: django-backend-service
#    env: python
#    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
#    startCommand: "gunicorn backend.wsgi:application"
#    envVars:
#      - key: DATABASE_URL
#        fromDatabase:
#          name: inventory_db
#          property: connectionString
#      - key: SECRET_KEY
#        generateValue: true
#      - key: WEB_CONCURRENCY
#        value: 4
#      - key: PYTHON_VERSION
#        value: 3.11.4
#
#  - type: static
#    name: flutter-frontend-service
#    env: static
#    rootDir: frontend
#    buildCommand: |
#      #!/usr/bin/env bash
#      set -o errexit
#      FLUTTER_VERSION="3.35.1"
#      FLUTTER_PATH="$HOME/flutter"
#      if [ ! -d "$FLUTTER_PATH" ]; then
#        git clone https://github.com/flutter/flutter.git --depth 1 --branch $FLUTTER_VERSION $FLUTTER_PATH
#      fi
#      export PATH="$FLUTTER_PATH/bin:$PATH"
#      flutter pub get
#      flutter build web --release
#    publishPath: "build/web"


databases:
  - name: inventory_db # IMPORTANT: Change this to the name of your database service on Render
    databaseName: inventory_db_vtra
    user: postgres

services:
  - type: web
    name: django-backend-service # Or your preferred name
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory_db # IMPORTANT: Change this to the name of your database service on Render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4

  - type: static
    name: flutter-frontend-service # Or your preferred name
    env: static
    rootDir: frontend
    buildCommand: |
      #!/usr/bin/env bash
      set -o errexit
      FLUTTER_VERSION="3.35.1"
      FLUTTER_PATH="$HOME/flutter"
      if [ ! -d "$FLUTTER_PATH" ]; then
        git clone https://github.com/flutter/flutter.git --depth 1 --branch $FLUTTER_VERSION $FLUTTER_PATH
      fi
      export PATH="$FLUTTER_PATH/bin:$PATH"
      flutter pub get
      flutter build web --release
    publishPath: "build/web"