# Generated by Django 5.2.5 on 2025-08-23 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_inwardentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="style",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="inwardentry",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inward_entries",
                to="api.material",
            ),
        ),
        migrations.AlterField(
            model_name="inwardentry",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="material",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_orders",
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="productmaterialmapping",
            name="fixed_quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
