# Generated by Django 5.2.5 on 2025-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="low_stock_threshold",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
